import type {
  BaseFacilityDefinition,
  CardTableEntry,
  DeclarativeRule,
  ScenarioSiteDefinition,
  VehicleDefinition,
} from "./types";

const player = (page: number, section: string) => ({ manual: "players" as const, page, section });
const referee = (page: number, section: string) => ({ manual: "referees" as const, page, section });

/** Character construction and advancement rules independent of any UI. */
export const CHARACTER_RULE_CATALOG: readonly DeclarativeRule[] = [
  { id: "character.attribute-baseline", domain: "character", source: player(20, "Character Creation: Archetypes"), when: [], effects: [{ operation: "set", target: "character.attributes", value: "STR:C,AGL:C,INT:C,EMP:C" }, { operation: "set", target: "character.attributeIncreases", value: 3 }], summary: "Archetype characters begin with C in every attribute and three one-step increases." },
  { id: "character.attribute-tradeoff", domain: "character", source: player(20, "Character Creation: Archetypes"), when: [{ fact: "character.attributeReducedFromBaseline", operator: "equals", value: true }], effects: [{ operation: "add", target: "character.attributeIncreases", value: 1 }], summary: "Reducing one baseline C attribute to D grants one additional increase." },
  { id: "character.starting-skills", domain: "character", source: player(20, "Character Creation: Archetypes"), when: [], effects: [{ operation: "set", target: "character.startingSkillAllocation", value: "B:1,C:2,D:3" }], summary: "Archetype creation assigns one B, two C, and three D skills." },
  { id: "character.hit-capacity", domain: "character", source: player(16, "Hit and Stress Capacity"), when: [], effects: [{ operation: "set", target: "character.hitCapacityFormula", value: "ceil((STR.dieSize + AGL.dieSize) / 4)" }], summary: "Hit capacity is the rounded-up sum of Strength and Agility die sizes divided by four." },
  { id: "character.stress-capacity", domain: "character", source: player(16, "Hit and Stress Capacity"), when: [], effects: [{ operation: "set", target: "character.stressCapacityFormula", value: "ceil((INT.dieSize + EMP.dieSize) / 4)" }], summary: "Stress capacity is the rounded-up sum of Intelligence and Empathy die sizes divided by four." },
  { id: "character.unit-morale", domain: "character", source: player(16, "Unit Morale"), when: [], effects: [{ operation: "set", target: "unit.moraleFormula", value: "highestPartyCommandSkill" }], summary: "Starting unit morale equals the group's highest Command skill." },
  { id: "character.moral-code-followed", domain: "character", source: player(17, "Moral Code"), when: [{ fact: "character.followedMoralCodeAtCost", operator: "equals", value: true }], effects: [{ operation: "add", target: "relatedSkill.modifier", value: 1 }, { operation: "add", target: "session.experience", value: 1 }], summary: "Following a moral code at material cost grants a related +1 and session XP." },
  { id: "character.moral-code-betrayed", domain: "character", source: player(17, "Moral Code"), when: [{ fact: "character.betrayedMoralCode", operator: "equals", value: true }], effects: [{ operation: "add", target: "actor.stress", value: 1 }], summary: "Betraying a moral code immediately inflicts one stress." },
  { id: "character.backpack-capacity", domain: "character", source: player(19, "Encumbrance"), when: [{ fact: "actor.hasBackpack", operator: "equals", value: true }], effects: [{ operation: "set", target: "backpack.capacityFormula", value: "STR.dieSize" }, { operation: "add", target: "mobility.modifier", value: -2 }], summary: "A backpack adds Strength-die-size capacity and applies Mobility -2 while carried." },
  { id: "character.starting-vehicle", domain: "character", source: player(18, "Vehicle"), when: [], effects: [{ operation: "set", target: "startingVehicle.roll", value: "2D6 + partySize" }], summary: "Starting vehicle category comes from 2D6 plus party size: none, 2WD, pickup, jeep/HMMWV, APC, or MBT." },
];

export const VEHICLE_DATA: readonly VehicleDefinition[] = [
  { id: "horse", name: "Horse", source: player(116, "Civilian Vehicles"), category: "animal", reliability: null, combatSpeed: { onRoad: 2, offRoad: 2 }, travelSpeed: { onRoad: 3, offRoad: 2 }, armor: { front: 0, side: 0, rear: 0 }, fuel: { type: null, capacityLitres: null, litresPerHex: null }, crew: 1, passengerCapacity: 1, cargoEncumbrance: 25, mainWeapon: null, secondaryWeapons: [], price: 500 },
  { id: "bicycle", name: "Bicycle", source: player(116, "Civilian Vehicles"), category: "bicycle", reliability: 5, combatSpeed: { onRoad: 2, offRoad: 1, drivetrain: "wheeled" }, travelSpeed: { onRoad: 4, offRoad: 2 }, armor: { front: 0, side: 0, rear: 0 }, fuel: { type: null, capacityLitres: null, litresPerHex: null }, crew: 1, passengerCapacity: 0, cargoEncumbrance: 5, mainWeapon: null, secondaryWeapons: [], price: 50 },
  { id: "motorcycle", name: "Motorcycle", source: player(116, "Civilian Vehicles"), category: "motorcycle", reliability: 5, combatSpeed: { onRoad: 6, offRoad: 1, drivetrain: "wheeled" }, travelSpeed: { onRoad: 9, offRoad: 2 }, armor: { front: 0, side: 0, rear: 0 }, fuel: { type: "gasoline", capacityLitres: 20, litresPerHex: 0.5 }, crew: 1, passengerCapacity: 1, cargoEncumbrance: 25, mainWeapon: null, secondaryWeapons: [], price: 3000 },
  { id: "2wd-car", name: "2WD Car", source: player(116, "Civilian Vehicles"), category: "car", reliability: 5, combatSpeed: { onRoad: 6, offRoad: 1, drivetrain: "wheeled" }, travelSpeed: { onRoad: 10, offRoad: 1 }, armor: { front: 1, side: 1, rear: 1 }, fuel: { type: "gasoline", capacityLitres: 60, litresPerHex: 1 }, crew: 1, passengerCapacity: 3, cargoEncumbrance: 75, mainWeapon: null, secondaryWeapons: [], price: 4000, traits: ["gasoline-or-diesel"] },
  { id: "4wd-car", name: "4WD Car", source: player(116, "Civilian Vehicles"), category: "car", reliability: 5, combatSpeed: { onRoad: 6, offRoad: 3, drivetrain: "wheeled" }, travelSpeed: { onRoad: 10, offRoad: 6 }, armor: { front: 1, side: 1, rear: 1 }, fuel: { type: "gasoline", capacityLitres: 80, litresPerHex: 2 }, crew: 1, passengerCapacity: 3, cargoEncumbrance: 75, mainWeapon: null, secondaryWeapons: [], price: 10000, traits: ["gasoline-or-diesel"] },
  { id: "pickup-truck", name: "Pickup Truck", source: player(116, "Civilian Vehicles"), category: "truck", reliability: 5, combatSpeed: { onRoad: 5, offRoad: 3, drivetrain: "wheeled" }, travelSpeed: { onRoad: 9, offRoad: 4 }, armor: { front: 1, side: 1, rear: 1 }, fuel: { type: "gasoline", capacityLitres: 100, litresPerHex: 2 }, crew: 1, passengerCapacity: 5, cargoEncumbrance: 250, mainWeapon: null, secondaryWeapons: [], price: 8000 },
  { id: "m998-hmmwv", name: "M998 HMMWV", source: player(116, "US Military Vehicles"), category: "4wd-car", reliability: 5, combatSpeed: { onRoad: 5, offRoad: 4, drivetrain: "wheeled" }, travelSpeed: { onRoad: 10, offRoad: 8 }, armor: { front: 1, side: 1, rear: 1 }, fuel: { type: "gasoline", capacityLitres: 95, litresPerHex: 3 }, crew: 1, passengerCapacity: 4, cargoEncumbrance: 100, mainWeapon: "M240B (pintle)", secondaryWeapons: ["radio"], price: 15000 },
  { id: "m113a3", name: "M113A3", source: player(117, "US Military Vehicles"), category: "apc", reliability: 5, combatSpeed: { onRoad: 4, offRoad: 3, drivetrain: "tracked" }, travelSpeed: { onRoad: 8, offRoad: 6 }, armor: { front: 4, side: 4, rear: 4 }, fuel: { type: "diesel", capacityLitres: 360, litresPerHex: 8 }, crew: 2, passengerCapacity: 11, cargoEncumbrance: 275, mainWeapon: "M2HB (pintle gun shield)", secondaryWeapons: ["smoke-dischargers", "radio"], price: 125000 },
  { id: "bradley-m2-m3", name: "Bradley M2/M3", source: player(117, "US Military Vehicles"), category: "ifv", reliability: 5, combatSpeed: { onRoad: 5, offRoad: 4, drivetrain: "tracked" }, travelSpeed: { onRoad: 9, offRoad: 8 }, armor: { front: 5, side: 4, rear: 4 }, fuel: { type: "diesel", capacityLitres: 360, litresPerHex: 12 }, crew: 3, passengerCapacity: 7, cargoEncumbrance: 175, mainWeapon: "25mm turret", secondaryWeapons: ["M240B coaxial", "TOW x2", "smoke-dischargers", "radio"], price: 250000 },
  { id: "m1a1-abrams", name: "M1A1 Abrams", source: player(118, "US Military Vehicles"), category: "mbt", reliability: 5, combatSpeed: { onRoad: 5, offRoad: 4, drivetrain: "tracked" }, travelSpeed: { onRoad: 10, offRoad: 9 }, armor: { front: 12, side: 8, rear: 6 }, fuel: { type: "gasoline", capacityLitres: 1915, litresPerHex: 40 }, crew: 4, passengerCapacity: 0, cargoEncumbrance: 0, mainWeapon: "120mm turret (FCS)", secondaryWeapons: ["M2HB", "M240B coaxial", "M240B pintle", "smoke-dischargers", "radio"], price: 1000000 },
  { id: "btr-80", name: "BTR-80", source: player(120, "Soviet Military Vehicles"), category: "apc", reliability: 5, combatSpeed: { onRoad: 4, offRoad: 3, drivetrain: "wheeled" }, travelSpeed: { onRoad: 10, offRoad: 6 }, armor: { front: 4, side: 4, rear: 4 }, fuel: { type: "diesel", capacityLitres: 300, litresPerHex: 6 }, crew: 2, passengerCapacity: 7, cargoEncumbrance: 175, mainWeapon: "30mm turret", secondaryWeapons: ["PKM coaxial", "radio"], price: 100000 },
  { id: "t-72", name: "T-72", source: player(120, "Soviet Military Vehicles"), category: "mbt", reliability: 5, combatSpeed: { onRoad: 5, offRoad: 4, drivetrain: "tracked" }, travelSpeed: { onRoad: 9, offRoad: 8 }, armor: { front: 9, side: 8, rear: 5 }, fuel: { type: "diesel", capacityLitres: 1200, litresPerHex: 24 }, crew: 3, passengerCapacity: 0, cargoEncumbrance: 0, mainWeapon: "125mm turret (FCS)", secondaryWeapons: ["PKM coaxial", "NSV pintle", "smoke-dischargers", "radio"], price: 700000 },
];

export const BASE_FACILITY_DATA: readonly BaseFacilityDefinition[] = [
  { id: "cow-pen", name: "Cow Pen", source: player(134, "Facilities"), prerequisites: ["basic-tools", "cow"], constructionTime: "1 day", requiredSkills: ["STAMINA (Builder)"], effects: [{ operation: "set", target: "base.cowCapacity", value: 1 }, { operation: "set", target: "base.dailyMilkFormula", value: "2D6 domestic rations" }, { operation: "set", target: "base.cowSlaughterFormula", value: "2D6*6 domestic rations" }] },
  { id: "cropland", name: "Cropland", source: player(134, "Facilities"), prerequisites: ["plot-of-land", "basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Farmer)"], effects: [{ operation: "set", target: "base.fallHarvestFormula", value: "D6*100 wild food per success" }], },
  { id: "defenses", name: "Defenses", source: player(134, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "COMMAND (Tactician)"], effects: [{ operation: "set", target: "base.defensiveCoverArmor.minimum", value: 3 }] },
  { id: "heater", name: "Heater", source: player(134, "Facilities"), prerequisites: ["basic-tools", "firewood-or-alcohol-fuel:5L/day"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "SURVIVAL (Quartermaster)"], effects: [{ operation: "block", target: "base.coldEffects" }] },
  { id: "infirmary", name: "Infirmary", source: player(134, "Facilities"), prerequisites: ["basic-tools", "alcohol-fuel"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "MEDICAL AID (General Practitioner)"], effects: [{ operation: "add", target: "medicalAid.modifier", value: 1 }] },
  { id: "garage", name: "Garage", source: player(134, "Facilities"), prerequisites: ["basic-tools", "general-spare-parts:50"], constructionTime: "2 weeks", requiredSkills: ["STAMINA (Builder)", "TECH (Blacksmith)"], effects: [{ operation: "add", target: "vehicleRepair.techModifier", value: 1 }, { operation: "set", target: "base.vehicleConstruction.enabled", value: true }] },
  { id: "lookout", name: "Lookout", source: player(134, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)"], effects: [{ operation: "add", target: "base.spotApproachingEnemiesModifier", value: 1 }, { operation: "set", target: "base.lookoutCoverArmor", value: 2 }] },
  { id: "pigsty", name: "Pigsty", source: player(134, "Facilities"), prerequisites: ["basic-tools", "pigs"], constructionTime: "1 day", requiredSkills: ["STAMINA (Builder)"], effects: [{ operation: "set", target: "base.pigCapacity", value: 12 }, { operation: "set", target: "base.pigSlaughterFormula", value: "2D6*2 domestic rations" }] },
  { id: "prison-cells", name: "Prison Cells", source: player(134, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)"], effects: [{ operation: "set", target: "base.prisonerCapacity", value: 12 }, { operation: "set", target: "base.prisonDoorArmor", value: 2 }] },
  { id: "root-cellar", name: "Root Cellar", source: player(134, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "SURVIVAL (Cook)"], effects: [{ operation: "set", target: "domesticFood.shelfLife", value: "1 month" }] },
  { id: "shrine", name: "Shrine", source: player(134, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "MEDICAL AID (Counselor)"], effects: [{ operation: "add", target: "actor.stressRecovery", value: 1 }], },
  { id: "well", name: "Well", source: player(135, "Facilities"), prerequisites: ["basic-tools"], constructionTime: "2 weeks", requiredSkills: ["STAMINA (Builder)", "SURVIVAL (Quartermaster)"], effects: [{ operation: "set", target: "base.cleanWaterAccess", value: true }] },
  { id: "windmill", name: "Windmill", source: player(135, "Facilities"), prerequisites: ["basic-tools", "general-spare-parts:40", "electronic-spare-parts:40"], constructionTime: "1 week", requiredSkills: ["STAMINA (Builder)", "TECH (Blacksmith, Electrician)"], effects: [{ operation: "set", target: "base.power.capacity", value: "one-large-or-twelve-small-devices" }], },
  { id: "workshop", name: "Workshop", source: player(135, "Facilities"), prerequisites: ["basic-tools", "general-spare-parts:50"], constructionTime: "2 weeks", requiredSkills: ["STAMINA (Builder)", "TECH (Blacksmith)"], effects: [{ operation: "add", target: "tech.repairModifier", value: 1 }] },
];

export const SOLO_ENCOUNTER_TABLE: readonly CardTableEntry[] = [
  { card: "2", values: ["PCs", "fight", "personal-motive", "morale", "bond"] }, { card: "3", values: ["animal", "pack", "living", "dead", "single"] }, { card: "4", values: ["derelict-vehicle", "wrecked", "intact", "occupied", "stripped"] }, { card: "5", values: ["crater", "old", "irradiated", "grave", "fresh"] }, { card: "6", values: ["ruins", "civilian", "farm", "industrial", "military"] }, { card: "7", values: ["refugees", "foreign", "angry", "desperate", "local"] }, { card: "8", values: ["hunters", "in-camp", "scared", "drunk", "stealthy"] }, { card: "9", values: ["marauders", "raiding", "wounded", "prisoners", "ambush"] }, { card: "10", values: ["stragglers", "enemy", "pows", "deserters", "friendly"] }, { card: "jack", values: ["military-patrol", "trained", "veteran", "elite", "conscripts"] }, { card: "queen", values: ["military-outpost", "abandoned", "camp", "cantonment", "active"] }, { card: "king", values: ["military-convoy", "stopped", "under-fire", "destroyed", "moving"] }, { card: "ace", values: ["settlement", "rural", "industrial", "scenario-site", "camp"] },
];

export const SOLO_SETTLEMENT_TABLE: readonly CardTableEntry[] = [
  { card: "2", values: ["divided", "friendly"] }, { card: "3", values: ["under-siege", "curious"] }, { card: "4", values: ["gangs", "open-to-contact"] }, { card: "5", values: ["unclean-water", "wary-of-outsiders"] }, { card: "6", values: ["food-shortage", "neutral"] }, { card: "7", values: ["disease", "neutral"] }, { card: "8", values: ["feud", "neutral"] }, { card: "9", values: ["refugees", "frightened"] }, { card: "10", values: ["flooding", "defensive"] }, { card: "jack", values: ["missing-people", "traumatized"] }, { card: "queen", values: ["espionage", "bold"] }, { card: "king", values: ["absent-leader", "visionaries"] }, { card: "ace", values: ["tyrannical-leader", "hostile"] },
];

export const REFEREE_RULE_CATALOG: readonly DeclarativeRule[] = [
  { id: "solo.shift-procedure", domain: "referee", source: referee(102, "Solo Rules"), when: [], effects: [{ operation: "set", target: "solo.shiftProcedure", value: "weather,tasks,encounter,recon,resolve,oracle,next-shift" }], summary: "Solo play follows a seven-step procedure each travel shift." },
  { id: "solo.oracle-colour", domain: "referee", source: referee(103, "The Oracle"), when: [], effects: [{ operation: "set", target: "oracle.red", value: "helpful-or-yes" }, { operation: "set", target: "oracle.black", value: "hazardous-or-no" }], summary: "Oracle red suits mean helpful/yes and black suits mean hazardous/no." },
  { id: "solo.plot-point", domain: "referee", source: referee(105, "Plot Points"), when: [{ fact: "oracle.sameValueDrawCount", operator: "gte", value: 2 }], effects: [{ operation: "set", target: "solo.plotPoint", value: true }], summary: "Two or more drawn cards with the same value create a plot point." },
  { id: "conversion.npc-tier", domain: "referee", source: referee(107, "NPCs & Tasks"), when: [], effects: [{ operation: "set", target: "conversion.npcTiers", value: "novice:C/D/D,experienced:C/C/C,veteran:B/C/B,elite:B/B/A" }], summary: "Legacy NPC tiers map to 4e attribute/skill/CUF levels." },
  { id: "conversion.legacy-range", domain: "referee", source: referee(109, "Weapons"), when: [], effects: [{ operation: "set", target: "conversion.shortRangeFormula", value: "ceil(legacyRange / 10)" }], summary: "Convert legacy weapon range to 4e short range by dividing by ten and rounding up." },
  { id: "conversion.legacy-weight", domain: "referee", source: referee(109, "Weapons"), when: [], effects: [{ operation: "set", target: "conversion.weaponWeightFormula", value: "floor(legacyWeight / 3)" }], summary: "Convert legacy weapon weight by dividing by three and rounding down, retaining quarter/half units below one." },
];

/** Site metadata gives the world layer stable parent IDs for child entities. */
export const SCENARIO_SITE_DATA: readonly ScenarioSiteDefinition[] = [
  { id: "the-prison", name: "The Prison", source: referee(71, "Scenario Sites"), scale: { widthMetres: 200, heightMetres: 150 }, requiredSections: ["overview", "rumors", "situation", "arrival", "countdown", "locations", "npcs", "events"], locationCountRange: [5, 10], npcCountRange: [5, 10], eventCountRange: [5, 10], tags: ["prison", "religious-community", "intel", "redemption"] },
  { id: "americatown", name: "Americatown", source: referee(79, "Scenario Sites"), scale: { widthMetres: 200, heightMetres: 150 }, requiredSections: ["overview", "rumors", "situation", "arrival", "countdown", "locations", "npcs", "events"], locationCountRange: [5, 10], npcCountRange: [5, 10], eventCountRange: [5, 10], tags: ["occupation", "resistance", "town", "espionage"] },
  { id: "childrens-crusade", name: "The Children's Crusade", source: referee(86, "Scenario Sites"), scale: { widthMetres: 200, heightMetres: 150 }, requiredSections: ["overview", "rumors", "situation", "arrival", "countdown", "locations", "npcs", "events"], locationCountRange: [5, 10], npcCountRange: [5, 10], eventCountRange: [5, 10], tags: ["military-academy", "children", "pow", "survival"] },
  { id: "the-burnt-town", name: "The Burnt Town", source: referee(93, "Scenario Sites"), scale: { widthMetres: 200, heightMetres: 150 }, requiredSections: ["overview", "rumors", "situation", "arrival", "countdown", "locations", "npcs", "events"], locationCountRange: [5, 10], npcCountRange: [5, 10], eventCountRange: [5, 10], tags: ["burned-town", "marauders", "civilians", "conflict"] },
];
