import type { DeclarativeRule } from "./types";

/**
 * First machine-consumable pass of the Player's Manual's universal mechanics.
 * Values are mechanics, not display copy.  Rule IDs are stable API keys.
 */
export const CORE_RULE_CATALOG: readonly DeclarativeRule[] = [
  {
    id: "dice.success-threshold",
    domain: "dice",
    source: { manual: "players", page: 44, section: "Roll the Dice" },
    when: [{ fact: "die.result", operator: "gte", value: 6 }],
    effects: [{ operation: "add", target: "roll.successes", value: 1 }],
    summary: "A base-die result of 6 or greater produces a success.",
  },
  {
    id: "dice.double-success-threshold",
    domain: "dice",
    source: { manual: "players", page: 44, section: "Roll the Dice" },
    when: [{ fact: "die.result", operator: "gte", value: 10 }],
    effects: [{ operation: "set", target: "die.successes", value: 2 }],
    summary: "A D10 or D12 result of 10 or greater produces two successes.",
  },
  {
    id: "dice.base-die-steps",
    domain: "dice",
    source: { manual: "players", page: 44, section: "Base Dice" },
    when: [],
    effects: [{ operation: "set", target: "dice.stepOrder", value: "D6,D8,D10,D12" }],
    summary: "Letter levels map from D through A to D6, D8, D10, and D12.",
  },
  {
    id: "dice.push.once",
    domain: "dice",
    source: { manual: "players", page: 45, section: "Pushing Your Roll" },
    when: [{ fact: "roll.pushCount", operator: "equals", value: 0 }],
    effects: [{ operation: "set", target: "roll.pushCount", value: 1 }],
    summary: "An active skill roll can be pushed at most once.",
  },
  {
    id: "dice.push.attribute-cost",
    domain: "dice",
    source: { manual: "players", page: 45, section: "Pushing Your Roll" },
    when: [{ fact: "roll.pushed", operator: "equals", value: true }],
    effects: [
      { operation: "add", target: "actor.damage", value: 1 },
      { operation: "add", target: "actor.stress", value: 1 },
    ],
    summary: "Each bane rolled while pushing costs damage for STR/AGL or stress for INT/EMP; consumers select the applicable target.",
  },
  {
    id: "dice.modifier-bounds",
    domain: "dice",
    source: { manual: "players", page: 45, section: "Modifiers" },
    when: [],
    effects: [
      { operation: "set", target: "dice.maximum", value: "2D12" },
      { operation: "set", target: "dice.minimum", value: "1D6" },
    ],
    summary: "Modifiers balance lower dice first; the pool is bounded by two D12s and one D6.",
  },
  {
    id: "dice.help.maximum",
    domain: "dice",
    source: { manual: "players", page: 46, section: "Help From Others" },
    when: [],
    effects: [{ operation: "set", target: "roll.helpModifier.maximum", value: 3 }],
    summary: "Each valid helper adds one step, capped at three helpers.",
  },
  {
    id: "dice.opposed.cancel-successes",
    domain: "dice",
    source: { manual: "players", page: 46, section: "Opposed Rolls" },
    when: [{ fact: "roll.kind", operator: "equals", value: "opposed" }],
    effects: [{ operation: "add", target: "active.successes", value: -1 }],
    summary: "Each opposing success cancels one active success; the active side must retain more successes.",
  },
  {
    id: "combat.damage.extra-success",
    domain: "combat",
    source: { manual: "players", page: 48, section: "The Skills" },
    when: [{ fact: "attack.successes", operator: "gte", value: 2 }],
    effects: [{ operation: "add", target: "attack.damage", value: 1 }],
    summary: "Every attack success beyond the first adds one damage.",
  },
  {
    id: "condition.starving",
    domain: "condition",
    source: { manual: "players", page: 78, section: "Starving" },
    when: [{ fact: "actor.daysWithoutFood", operator: "gte", value: 1 }],
    effects: [
      { operation: "set", target: "actor.condition.starving", value: true },
      { operation: "block", target: "actor.damageRecovery" },
      { operation: "schedule", target: "actor.damage", value: 1, timing: "week" },
    ],
    summary: "After a full day without food, damage recovery stops and starvation inflicts weekly damage.",
  },
  {
    id: "condition.dehydrated",
    domain: "condition",
    source: { manual: "players", page: 78, section: "Dehydrated" },
    when: [{ fact: "actor.daysWithoutWater", operator: "gte", value: 1 }],
    effects: [
      { operation: "set", target: "actor.condition.dehydrated", value: true },
      { operation: "block", target: "actor.damageRecovery" },
      { operation: "schedule", target: "actor.damage", value: 1, timing: "day" },
    ],
    summary: "After one day without water, damage recovery stops and dehydration inflicts daily damage.",
  },
  {
    id: "condition.sleep-deprived",
    domain: "condition",
    source: { manual: "players", page: 78, section: "Sleep Deprived" },
    when: [{ fact: "actor.daysWithoutSleep", operator: "gte", value: 1 }],
    effects: [
      { operation: "set", target: "actor.condition.sleepDeprived", value: true },
      { operation: "block", target: "actor.stressRecovery" },
      { operation: "schedule", target: "actor.stress", value: 1, timing: "day" },
    ],
    summary: "After one day without sleep, stress recovery stops and sleep deprivation inflicts daily stress.",
  },
  {
    id: "environment.falling",
    domain: "environment",
    source: { manual: "players", page: 79, section: "Falling" },
    when: [{ fact: "event.kind", operator: "equals", value: "fall" }],
    effects: [
      { operation: "set", target: "damage.formula", value: "floor(fallHeightMeters / 2)" },
      { operation: "set", target: "critical.threshold", value: 3 },
      { operation: "block", target: "armor.protection" },
    ],
    summary: "Falls inflict half the height in metres, rounded down; armour does not protect.",
  },
  {
    id: "environment.drowning",
    domain: "environment",
    source: { manual: "players", page: 79, section: "Drowning" },
    when: [{ fact: "actor.drowning", operator: "equals", value: true }],
    effects: [{ operation: "schedule", target: "actor.damage", value: 1, timing: "round" }],
    summary: "Drowning inflicts one damage every round after a failed breath-holding roll.",
  },
  {
    id: "environment.fire",
    domain: "environment",
    source: { manual: "players", page: 79, section: "Fire" },
    when: [{ fact: "event.kind", operator: "equals", value: "fire" }],
    effects: [
      { operation: "roll", target: "fire.attack", dice: "2<fireIntensity>" },
      { operation: "block", target: "armor.protection" },
      { operation: "set", target: "critical.threshold", value: 2 },
    ],
    summary: "Fire attacks use two intensity dice; successes are damage and armour does not protect.",
  },
  {
    id: "environment.chemical-radius",
    domain: "environment",
    source: { manual: "players", page: 79, section: "Chemical Warfare" },
    when: [],
    effects: [{ operation: "set", target: "chemical.radiusByBlastPower", value: "A:3,B:2,C:1,D:0" }],
    summary: "Chemical blast radius in hexes is A=3, B=2, C=1, D=target only.",
  },
  {
    id: "environment.radiation-hotspot",
    domain: "environment",
    source: { manual: "players", page: 80, section: "Hotspots" },
    when: [{ fact: "actor.inRadiationHotspot", operator: "equals", value: true }],
    effects: [{ operation: "set", target: "radiation.frequency", value: "weak:shift,strong:stretch,extreme:round" }],
    summary: "Radiation hotspots add one rad per shift, stretch, or round by severity.",
  },
  {
    id: "environment.radiation-virulence",
    domain: "environment",
    source: { manual: "players", page: 80, section: "Radiation" },
    when: [{ fact: "actor.rads", operator: "gte", value: 1 }],
    effects: [{ operation: "set", target: "disease.virulenceFormula", value: "4 - actor.rads" }],
    summary: "Each rad triggers a radiation-sickness resistance roll with virulence 4 minus total rads.",
  },
  {
    id: "environment.disease",
    domain: "environment",
    source: { manual: "players", page: 81, section: "Disease" },
    when: [{ fact: "infection.rollSucceeded", operator: "equals", value: false }],
    effects: [
      { operation: "add", target: "actor.damage", value: 1 },
      { operation: "block", target: "actor.damageRecovery" },
      { operation: "schedule", target: "infection.roll", timing: "day" },
    ],
    summary: "A failed infection roll inflicts damage, prevents damage recovery, and repeats daily until success.",
  },
];
