import type { GearDefinition, WeaponDefinition } from "./types";

const source = (page: number, section: string) => ({
  manual: "players" as const,
  page,
  section,
});

type WeaponInput = Omit<WeaponDefinition, "source"> & { page: number; section: string };

const weapon = ({ page, section, ...definition }: WeaponInput): WeaponDefinition => ({
  ...definition,
  source: source(page, section),
});

/**
 * Normalized weapon tables.  All dimensions use the manual's tactical units:
 * range is 10m hexes, weight is encumbrance, and price is ammunition rounds.
 */
export const WEAPON_DATA: readonly WeaponDefinition[] = [
  weapon({ id: "unarmed", name: "Unarmed", page: 93, section: "Melee Weapons", category: "unarmed", ammunition: null, reliability: 5, rateOfFire: null, damage: 1, criticalThreshold: 4, blastPower: null, shortRangeHexes: null, magazineCapacity: null, armorModifier: 3, encumbrance: 0, price: null }),
  weapon({ id: "knife", name: "Knife", page: 93, section: "Melee Weapons", category: "melee", ammunition: null, reliability: 5, rateOfFire: null, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: null, magazineCapacity: null, armorModifier: 1, encumbrance: 0.25, price: 5 }),
  weapon({ id: "club", name: "Club", page: 93, section: "Melee Weapons", category: "melee", ammunition: null, reliability: 5, rateOfFire: null, damage: 2, criticalThreshold: 4, blastPower: null, shortRangeHexes: null, magazineCapacity: null, armorModifier: 2, encumbrance: 1, price: 1, traits: ["jury-riggable"] }),
  weapon({ id: "machete", name: "Machete", page: 93, section: "Melee Weapons", category: "melee", ammunition: null, reliability: 5, rateOfFire: null, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: null, magazineCapacity: null, armorModifier: 1, encumbrance: 0.5, price: 20 }),
  weapon({ id: "axe", name: "Axe", page: 93, section: "Melee Weapons", category: "melee", ammunition: null, reliability: 5, rateOfFire: null, damage: 3, criticalThreshold: 3, blastPower: null, shortRangeHexes: null, magazineCapacity: null, armorModifier: 1, encumbrance: 1, price: 30 }),
  weapon({ id: "hunting-bow", name: "Hunting Bow", page: 94, section: "Bows & Thrown", category: "bow", ammunition: "arrow", reliability: 5, rateOfFire: 1, damage: 1, criticalThreshold: 2, blastPower: null, shortRangeHexes: 4, magazineCapacity: 1, armorModifier: 1, encumbrance: 1, price: 150 }),
  weapon({ id: "crossbow", name: "Crossbow", page: 94, section: "Bows & Thrown", category: "bow", ammunition: "bolt", reliability: 5, rateOfFire: 1, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 4, magazineCapacity: 1, armorModifier: 0, encumbrance: 1, price: 200 }),
  weapon({ id: "police-pistol", name: "Police Pistol", page: 94, section: "Civilian Firearms", category: "pistol", ammunition: "9x19", reliability: 5, rateOfFire: 2, damage: 1, criticalThreshold: 2, blastPower: null, shortRangeHexes: 2, magazineCapacity: 17, armorModifier: 1, encumbrance: 0.5, price: 125 }),
  weapon({ id: "service-revolver", name: "Service Revolver", page: 94, section: "Civilian Firearms", category: "revolver", ammunition: ".38 SPL", reliability: 5, rateOfFire: 2, damage: 1, criticalThreshold: 3, blastPower: null, shortRangeHexes: 2, magazineCapacity: 6, armorModifier: 2, encumbrance: 0.5, price: 75 }),
  weapon({ id: "bolt-action-rifle", name: "Bolt-action Rifle", page: 95, section: "Civilian Firearms", category: "hunting-rifle", ammunition: ".30-06", reliability: 5, rateOfFire: 1, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: 10, magazineCapacity: 5, armorModifier: 0, encumbrance: 1, price: 300 }),
  weapon({ id: "lever-action-rifle", name: "Lever-action Rifle", page: 95, section: "Civilian Firearms", category: "hunting-rifle", ammunition: ".30-30", reliability: 5, rateOfFire: 1, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: 5, magazineCapacity: 8, armorModifier: 0, encumbrance: 1, price: 250 }),
  weapon({ id: "semi-auto-shotgun", name: "Semi-auto Shotgun", page: 95, section: "Civilian Firearms", category: "shotgun", ammunition: "12 GA", reliability: 5, rateOfFire: 2, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: 2, magazineCapacity: 5, armorModifier: 1, encumbrance: 1, price: 225 }),
  weapon({ id: "pump-action-shotgun", name: "Pump-action Shotgun", page: 96, section: "Civilian Firearms", category: "shotgun", ammunition: "12 GA", reliability: 5, rateOfFire: 1, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: 2, magazineCapacity: 5, armorModifier: 1, encumbrance: 1, price: 200 }),
  weapon({ id: "m16a1", name: "M16A1", page: 97, section: "US Military Weapons", category: "assault-rifle", ammunition: "5.56x45", reliability: 5, rateOfFire: 6, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 5, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 400 }),
  weapon({ id: "m16a2", name: "M16A2", page: 97, section: "US Military Weapons", category: "assault-rifle", ammunition: "5.56x45", reliability: 5, rateOfFire: 3, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 6, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 400 }),
  weapon({ id: "m4", name: "M4", page: 97, section: "US Military Weapons", category: "carbine", ammunition: "5.56x45", reliability: 5, rateOfFire: 3, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 4, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 350 }),
  weapon({ id: "m4a1", name: "M4A1", page: 97, section: "US Military Weapons", category: "carbine", ammunition: "5.56x45", reliability: 5, rateOfFire: 6, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 4, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 375 }),
  weapon({ id: "m40a3", name: "M40A3", page: 98, section: "US Military Weapons", category: "sniper-rifle", ammunition: "7.62x51", reliability: 5, rateOfFire: 1, damage: 3, criticalThreshold: 3, blastPower: null, shortRangeHexes: 12, magazineCapacity: 5, armorModifier: 0, encumbrance: 2, price: 500 }),
  weapon({ id: "m82a1", name: "M82A1", page: 98, section: "US Military Weapons", category: "sniper-rifle", ammunition: ".50 M2", reliability: 5, rateOfFire: 1, damage: 4, criticalThreshold: 3, blastPower: null, shortRangeHexes: 20, magazineCapacity: 10, armorModifier: 0, encumbrance: 5, price: 1000 }),
  weapon({ id: "m249", name: "M249", page: 99, section: "US Military Weapons", category: "lmg", ammunition: "5.56x45", reliability: 5, rateOfFire: 6, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 6, magazineCapacity: 200, armorModifier: 0, encumbrance: 2, price: 1000, traits: ["bipod"] }),
  weapon({ id: "m240b", name: "M240B", page: 99, section: "US Military Weapons", category: "gpmg", ammunition: "7.62x51", reliability: 5, rateOfFire: 4, damage: 3, criticalThreshold: 4, blastPower: null, shortRangeHexes: 8, magazineCapacity: 100, armorModifier: 0, encumbrance: 3, price: 1500, traits: ["bipod"] }),
  weapon({ id: "m2hb", name: "M2HB", page: 99, section: "US Military Weapons", category: "hmg", ammunition: ".50 M2", reliability: 5, rateOfFire: 4, damage: 4, criticalThreshold: 4, blastPower: null, shortRangeHexes: 15, magazineCapacity: 100, armorModifier: 0, encumbrance: 7, price: 2000, traits: ["requires-tripod-or-vehicle-mount"] }),
  weapon({ id: "m72a3-law", name: "M72A3 LAW", page: 100, section: "US Military Weapons", category: "atrl", ammunition: "66mm", reliability: 5, rateOfFire: 1, damage: 6, criticalThreshold: 3, blastPower: "C", shortRangeHexes: 3, magazineCapacity: 1, armorModifier: -1, encumbrance: 1, price: 100, traits: ["disposable"] }),
  weapon({ id: "m136-at4", name: "M136 AT4", page: 100, section: "US Military Weapons", category: "atrl", ammunition: "84mm", reliability: 5, rateOfFire: 1, damage: 8, criticalThreshold: 2, blastPower: "C", shortRangeHexes: 5, magazineCapacity: 1, armorModifier: -1, encumbrance: 2, price: 200, traits: ["disposable"] }),
  weapon({ id: "akm", name: "AKM", page: 104, section: "Soviet Military Weapons", category: "assault-rifle", ammunition: "7.62x39", reliability: 5, rateOfFire: 4, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 5, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 300 }),
  weapon({ id: "ak-74", name: "AK-74", page: 104, section: "Soviet Military Weapons", category: "assault-rifle", ammunition: "5.45x39", reliability: 5, rateOfFire: 5, damage: 2, criticalThreshold: 3, blastPower: null, shortRangeHexes: 6, magazineCapacity: 30, armorModifier: 0, encumbrance: 1, price: 400 }),
  weapon({ id: "rpg-7v", name: "RPG-7V", page: 104, section: "Soviet Military Weapons", category: "atrl", ammunition: "83mm", reliability: 5, rateOfFire: 1, damage: 7, criticalThreshold: 2, blastPower: "C", shortRangeHexes: 6, magazineCapacity: 1, armorModifier: -1, encumbrance: 2, price: 750 }),
  weapon({ id: "fragmentation-grenade", name: "Fragmentation Grenade", page: 112, section: "Hand Grenades", category: "grenade", ammunition: null, reliability: 5, rateOfFire: 1, damage: 2, criticalThreshold: 3, blastPower: "C", shortRangeHexes: 3, magazineCapacity: 1, armorModifier: 1, encumbrance: 0.25, price: 30, traits: ["thrown"] }),
  weapon({ id: "anti-tank-grenade", name: "Anti-tank Grenade", page: 112, section: "Hand Grenades", category: "grenade", ammunition: null, reliability: 5, rateOfFire: 1, damage: 6, criticalThreshold: 3, blastPower: "D", shortRangeHexes: 3, magazineCapacity: 1, armorModifier: -1, encumbrance: 0.25, price: 50, traits: ["thrown"] }),
  weapon({ id: "smoke-grenade", name: "Smoke Grenade", page: 112, section: "Hand Grenades", category: "grenade", ammunition: null, reliability: 5, rateOfFire: 1, damage: null, criticalThreshold: null, blastPower: null, shortRangeHexes: 3, magazineCapacity: 1, armorModifier: 0, encumbrance: 0.25, price: 25, traits: ["thrown", "creates-smoke"] }),
  weapon({ id: "white-phosphorous-grenade", name: "White Phosphorous Grenade", page: 112, section: "Hand Grenades", category: "grenade", ammunition: null, reliability: 5, rateOfFire: 1, damage: null, criticalThreshold: null, blastPower: "B", shortRangeHexes: 3, magazineCapacity: 1, armorModifier: 0, encumbrance: 0.25, price: 50, traits: ["thrown", "fire-target-hex"] }),
];

const gear = (definition: GearDefinition): GearDefinition => definition;

/** Portable equipment with its rules effects expressed as structured data. */
export const GEAR_DATA: readonly GearDefinition[] = [
  gear({ id: "steel-helmet", name: "Steel Helmet", source: source(127, "Body Armor"), category: "armor", reliability: null, encumbrance: 1, price: 25, effects: [{ operation: "set", target: "armor.head", value: 1 }] }),
  gear({ id: "kevlar-helmet", name: "Kevlar Helmet", source: source(127, "Body Armor"), category: "armor", reliability: null, encumbrance: 0.5, price: 100, effects: [{ operation: "set", target: "armor.head", value: 1 }] }),
  gear({ id: "flak-jacket", name: "Flak Jacket", source: source(127, "Body Armor"), category: "armor", reliability: null, encumbrance: 1, price: 150, effects: [{ operation: "set", target: "armor.torso", value: 1 }] }),
  gear({ id: "plate-vest", name: "Plate Vest", source: source(127, "Body Armor"), category: "armor", reliability: null, encumbrance: 3, price: 250, effects: [{ operation: "set", target: "armor.torso", value: 2 }] }),
  gear({ id: "telescopic-sight", name: "Telescopic Sight", source: source(127, "Weapons Gear"), category: "weapon-accessory", reliability: null, encumbrance: 0, price: 100, effects: [{ operation: "add", target: "rangedCombat.modifier", value: 1 }], traits: ["slow-aim", "stable-platform-increases-modifier-to-2"] }),
  gear({ id: "night-vision-sight", name: "Night Vision Sight", source: source(127, "Weapons Gear"), category: "weapon-accessory", reliability: null, encumbrance: 0.5, price: 250, effects: [{ operation: "set", target: "darkness.rangedCombatPenalty", value: 0 }], traits: ["short-range-only", "requires-battery"] }),
  gear({ id: "bipod", name: "Bipod", source: source(127, "Weapons Gear"), category: "weapon-accessory", reliability: null, encumbrance: 0.25, price: 10, effects: [{ operation: "set", target: "weapon.stablePlatform", value: true }] }),
  gear({ id: "tripod", name: "Tripod", source: source(127, "Weapons Gear"), category: "weapon-accessory", reliability: null, encumbrance: 2, price: 25, effects: [{ operation: "set", target: "weapon.stablePlatform", value: true }], traits: ["required-for-some-heavy-weapons"] }),
  gear({ id: "binoculars", name: "Binoculars", source: source(129, "Observation Gear"), category: "observation", reliability: 1, encumbrance: 0.5, price: 50, effects: [{ operation: "add", target: "recon.modifier", value: 2 }], traits: ["active-scouting-or-observation-only"] }),
  gear({ id: "night-vision-goggles", name: "Night Vision Goggles", source: source(129, "Observation Gear"), category: "observation", reliability: 1, encumbrance: 0.5, price: 250, effects: [{ operation: "set", target: "darkness.rangedCombatAndReconPenalty", value: 0 }], traits: ["one-hex-vision", "two-hex-with-attached-ir-light", "attached-ir-light-enables-total-darkness", "requires-battery"] }),
  gear({ id: "thermal-optics", name: "Thermal Optics", source: source(129, "Observation Gear"), category: "observation", reliability: 1, encumbrance: 1, price: 1000, effects: [{ operation: "set", target: "visibility.darknessWeatherSmokePenalty", value: 0 }], traits: ["ignores-darkness-weather-smoke"] }),
  gear({ id: "compass", name: "Compass", source: source(129, "Observation Gear"), category: "observation", reliability: 1, encumbrance: 0.25, price: 10, effects: [{ operation: "add", target: "travel.navigationModifier", value: 2 }] }),
  gear({ id: "gps", name: "Global Positioning System", source: source(129, "Observation Gear"), category: "observation", reliability: null, encumbrance: 0.5, price: 250, effects: [{ operation: "block", target: "travel.navigationRoll" }], traits: ["requires-d6-result-4-or-higher-per-use"] }),
  gear({ id: "protective-mask", name: "Protective Mask", source: source(129, "Protective Gear"), category: "protective", reliability: 1, encumbrance: 0.5, price: 150, effects: [{ operation: "add", target: "chemical.staminaModifier", value: 3 }, { operation: "add", target: "recon.modifier", value: -2 }, { operation: "add", target: "travel.marchStaminaModifier", value: -2 }] }),
  gear({ id: "hazmat-suit", name: "Hazmat/MOPP Suit", source: source(130, "Protective Gear"), category: "protective", reliability: null, encumbrance: 1, price: 500, effects: [{ operation: "set", target: "chemical.protection", value: "full" }], traits: ["requires-protective-mask"] }),
  gear({ id: "raingear", name: "Raingear", source: source(130, "Protective Gear"), category: "protective", reliability: null, encumbrance: 0.5, price: 25, effects: [{ operation: "add", target: "chemical.staminaModifier", value: 1 }] }),
  gear({ id: "personal-medkit", name: "Personal Medkit", source: source(130, "Medical Supplies"), category: "medical", reliability: null, encumbrance: 0.25, price: 25, effects: [{ operation: "add", target: "medicalAid.modifier", value: 1 }], traits: ["single-use"] }),
  gear({ id: "doctors-medical-kit", name: "Doctor's Medical Kit", source: source(130, "Medical Supplies"), category: "medical", reliability: null, encumbrance: 2, price: 250, effects: [{ operation: "add", target: "medicalAid.modifier", value: 2 }], traits: ["contains-ten-doses-per-drug-type"] }),
  gear({ id: "antibiotics", name: "Antibiotics", source: source(130, "Medical Supplies"), category: "medical", reliability: null, encumbrance: 0, price: 25, effects: [{ operation: "add", target: "infection.medicalAidModifier", value: 3 }], traits: ["one-dose-lasts-one-day", "no-effect-on-viruses-or-radiation-sickness"] }),
  gear({ id: "pain-reliever", name: "Pain Reliever", source: source(130, "Medical Supplies"), category: "medical", reliability: null, encumbrance: 0, price: 15, effects: [{ operation: "add", target: "actor.damageRecovery", value: 1 }], traits: ["one-dose-per-shift-effective"] }),
  gear({ id: "atropine-autoinjector", name: "Atropine Autoinjector", source: source(130, "Medical Supplies"), category: "medical", reliability: null, encumbrance: 0, price: 100, effects: [{ operation: "block", target: "nerveAgent.deathSave" }], traits: ["single-use"] }),
  gear({ id: "small-still", name: "Small Still", source: source(130, "Fuel & Stills"), category: "fuel", reliability: 1, encumbrance: 20, price: 500, effects: [{ operation: "set", target: "alcoholFuel.litresPerShift", value: 5 }], traits: ["stationary", "one-organic-encumbrance-per-litre", "jury-riggable"] }),
  gear({ id: "large-still", name: "Large Still", source: source(131, "Fuel & Stills"), category: "fuel", reliability: 3, encumbrance: 400, price: 2500, effects: [{ operation: "set", target: "alcoholFuel.litresPerShift", value: 50 }], traits: ["stationary", "one-organic-encumbrance-per-litre", "jury-riggable"] }),
  gear({ id: "field-ration", name: "Field Ration", source: source(131, "Food & Drink"), category: "food", reliability: null, encumbrance: 0.25, price: 20, effects: [{ operation: "set", target: "actor.dailyFoodRequirement", value: 1 }] }),
  gear({ id: "domestic-food-ration", name: "Domestic Food Ration", source: source(131, "Food & Drink"), category: "food", reliability: null, encumbrance: 0.5, price: 10, effects: [{ operation: "set", target: "actor.dailyFoodRequirement", value: 1 }], traits: ["spoils-after-one-week"] }),
  gear({ id: "backpack", name: "Backpack", source: source(131, "Field Gear"), category: "field", reliability: null, encumbrance: 0, price: 50, effects: [{ operation: "set", target: "backpack.capacityFormula", value: "strengthDieSize" }, { operation: "add", target: "mobility.modifier", value: -2 }] }),
  gear({ id: "fatigues", name: "Fatigues", source: source(131, "Field Gear"), category: "field", reliability: null, encumbrance: 0, price: 20, effects: [{ operation: "add", target: "recon.infiltrationModifier", value: 1 }], traits: ["adequate-cold-clothing-except-severe-winter"] }),
  gear({ id: "sleeping-bag", name: "Sleeping Bag", source: source(131, "Field Gear"), category: "field", reliability: null, encumbrance: 1, price: 25, effects: [{ operation: "add", target: "survival.bareGroundSleepModifier", value: 2 }, { operation: "add", target: "cold.staminaModifier", value: 2 }] }),
  gear({ id: "small-tent", name: "Small Tent", source: source(131, "Field Gear"), category: "field", reliability: null, encumbrance: 4, price: 50, effects: [{ operation: "add", target: "travel.makeCampModifier", value: 1 }], traits: ["capacity:4"] }),
  gear({ id: "fishing-gear", name: "Fishing Gear", source: source(131, "Field Gear"), category: "field", reliability: null, encumbrance: 1, price: 25, effects: [{ operation: "set", target: "travel.fishing.enabled", value: true }], traits: ["jury-riggable"] }),
];
